language: node_js
node_js:
  - '10'

env:
  global:
    - DEV_IMAGE_NAME=luckjs/ts-luck-ui
    - DEV_CONTAINER_NAME=luck-ui_develop
    - DEV_VIRTUAL_HOST=app.testdevelop.luck.org.pl

    - PROD_IMAGE_NAME=luckjs/luck-ui
    - PROD_CONTAINER_NAME=luck-ui_master
    - PROD_VIRTUAL_HOST=app.luck.org.pl

jobs:
  include:
    - &build
      stage: build
      services:
        - docker
      script:
        - docker build . -t $IMAGE_NAME
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $IMAGE_NAME
      if: branch = develop
      env: IMAGE_NAME=$DEV_IMAGE_NAME

    - <<: *build
      before_script:
        - mv src/index.prod.html src/index.html
      if: branch = master
      env: IMAGE_NAME=$PROD_IMAGE_NAME

    - &deploy
      stage: deploy
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_e8fe58cdf4cd_key -iv $encrypted_e8fe58cdf4cd_iv
          -in .travis/id_rsa.enc -out .travis/id_rsa -d
        - eval "$(ssh-agent -s)"
        - cp .travis/id_rsa ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh-add ~/.ssh/id_rsa
        - chmod 700 ~/.ssh
        - ssh-keyscan $HOST_IP > ~/.ssh/known_hosts
      script: skip
      if: branch = develop
      env:
        - IMAGE_NAME=$DEV_IMAGE_NAME
        - CONTAINER_NAME=$DEV_CONTAINER_NAME
        - VIRTUAL_HOST=$DEV_VIRTUAL_HOST
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash .travis/deploy.sh $HOST_IP $DOCKER_PASSWORD $DOCKER_USERNAME $IMAGE_NAME $CONTAINER_NAME
          on:
            branch: develop

    - <<: *deploy
      if: branch = master
      env:
        - IMAGE_NAME=$PROD_IMAGE_NAME
        - CONTAINER_NAME=$PROD_CONTAINER_NAME
        - VIRTUAL_HOST=$PROD_VIRTUAL_HOST
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash .travis/deploy.sh $HOST_IP $DOCKER_PASSWORD $DOCKER_USERNAME $IMAGE_NAME $CONTAINER_NAME
          on:
            branch: master
            tags: true

